StevenEgnaczyk/DatabaseD

- .gitignore
- src/config/firebase.js
I think I did this right, never done this before
> Moved the firebase config files into its own file and gitignored it

- src/components/Startup/Login.jsx
- src/components/Startup/Signup.jsx
> 21 better fail message for an email already in use

- package-lock.json
- package.json
- src/App.jsx
- src/components/Startup/Login.jsx
- src/components/Startup/Signup.jsx
Changed UI of PopUp window from this
to this
Implemented using react-toastify
Fixes #33
> Fixed popup window UI better

- src/components/Home/FileQueryBar.css
- src/components/Home/FileQueryBar.jsx
- src/components/Home/NavBarLeft.css
- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
Not finished with this but if this works lets get it moved into main so people can begin styling the individual elements.
> Unfinished but more homepage styling for Main branch

- .gitignore
- src/components/Home/File.css
- src/components/Home/File.jsx
- src/components/Home/NavBar.css
- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
Added in grid system to the home page.
> Refactor file paths and update styling in Home page components.

- src/components/Home/FileQueryBar.jsx
Updated FileQueryBar.jsx to include functionality. 
Now, it needs to actually display filteredFiles
> Fix search bar functionality #50

- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
> Added paging for file previews

- src/Global.css
- src/components/Home/FileUpload.css
- src/components/Home/FileUpload.jsx
- src/components/Home/NavBar.css
- src/components/Home/NavBar.jsx
- src/pages/Home/Home.css
No issue assigned to this yet, but I made changes to the upload file button. Make sure that when you select a pdf it displays the name next to the submit button as well as a pdf preview.
> Some upload file changes.

- src/components/Home/File.css
- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
Made sure that all files have a uniform height. The borders also do not change depending on how many files are displayed.
> #71 added a dropdown to change how many files can be viewed per page.

- src/components/Home/File.jsx
the file preview needed its pathing changed since it is sending the file to a different directory. I can imagine this will need fixed again later
> issue #idk 

- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
- src/pages/Home/components/FileQueryBar.css
- src/pages/Home/components/NavBar.css
- src/pages/Home/components/NavBarLeft.css
Added styling as well as added fixed heights to components to make sure they stay with the viewport. When testing make sure that you can't scroll the main page and can only scroll the file display.
> new home and component styling.

- package-lock.json
- package.json
- src/Global.css
- src/pages/Home/Home.css
- src/pages/Home/components/Dropdowns/FilterDropdowns.css
- src/pages/Home/components/FileQueryBar.css
- src/pages/Home/components/NavBarLeft.css
- src/pages/Home/components/NavBarLeft.jsx
Added Icons on the navBarLeft. Be sure to install the react library that they are from. Improved the file display view with a new scroll bar and fixed paddings and styles. The navbar left buttons currently do nothing but I plan on adding features to them soon. Changes are in "kellen-working" branch
> big styling changes

- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
fixed the padding on the home screen and removed the pages per screen button and set the default pages per screen to 12.
> fixed padding

- package-lock.json
- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
- src/pages/Home/components/File.css
- src/pages/Home/components/File.jsx
- src/pages/Home/components/FileUpload.css
- src/pages/Home/components/FileUpload.jsx
Added a bookmark feature for the file previews. Updated the file upload screen to be a little cleaner. Moved the filter search bar into the container with the file previews for a cleaner scrolling experience. Added a grid svg to the bottom right for a future feature. Grid view as well as line view.
> more styling

- debug.log
- src/pages/Admin/Admin.css
- src/pages/Admin/Admin.jsx
- src/pages/Admin/components/TagsTabInterface.css
- src/pages/Admin/components/TagsTabInterface.jsx
- src/pages/Admin/components/UnapprovedUsers.css
- src/pages/Admin/components/UnapprovedUsers.jsx
- src/pages/Home/components/NavBar.css
- src/pages/Home/components/NavBar.jsx
* Separated unapproved user's table and tags tab components into their own separate jsx and css pages
* Added in base for how I want the admin page to look
* Approve and reject buttons work - delete someone from the database or approves them so they can log in
* Added in 'Home' navigation so you can get back to the home page from the Admin Page
*
> Admin Panel Additions

- src/pages/Home/components/FileSearchComponents/FileQueryBar.jsx
> fixed paths

- src/pages/Admin/components/TagsTabInterface.css
- src/pages/Admin/components/TagsTabInterface.jsx
Goo goo ga-ga accept my pull request yeh
> Added a tag for 'pending', 'active', or 'inactive' tags.

- src/pages/Home/components/NavBar.css
> changed spin

- src/pages/Home/Home.css
- src/pages/Home/components/SavedFilesComponents/SavedFiles.css
- src/pages/Home/components/SavedFilesComponents/SavedFilesPage.jsx
- src/pages/Home/components/SavedFilesComponents/SmallFileQueryBar.css
- src/pages/Home/components/SavedFilesComponents/SmallFileQueryBar.jsx
Updated the saved files page so that it has a different file query bar at the top but uses the same components as the home page search bar and buttons. Displayed the same files as on the main page, but once we set up the db we can update the page to only print the saved files.
> basic saved files page

- package-lock.json
- package.json
- src/index.js
- src/pages/Admin/Admin.css
- src/pages/Admin/Admin.jsx
- src/pages/Admin/components/CreateAssignmentType.jsx
- src/pages/Admin/components/CreateClass.jsx
- src/pages/Admin/components/CreateProfessor.jsx
- src/pages/Admin/components/CreateSemester.jsx
- src/pages/Admin/components/TagsTabInterface.css
- src/pages/Admin/components/TagsTabInterface.jsx
- src/pages/Admin/components/UnapprovedUsers.css
Things are in the admin panel. Made a skeleton for adding new tags and such.
> Been a while since I merged I forget all that I added but most

- src/App.jsx
- src/config/adminContext.js
- src/config/userContext.js
- src/pages/Admin/Admin.jsx
- src/pages/Admin/components/CreateModals/CreateModal.jsx
- src/pages/Home/components/Dropdowns/AssignmentType.jsx
- src/pages/Home/components/Dropdowns/ClassName.jsx
- src/pages/Home/components/Dropdowns/ProfessorName.jsx
- src/pages/Home/components/Dropdowns/Semester.jsx
- src/pages/Home/components/FileUpload.jsx
- src/pages/Home/components/NavBar.css
- src/pages/Home/components/NavBar.jsx
- src/pages/StartupScreen/components/AboutPage.jsx
- src/pages/StartupScreen/components/Signup.jsx
Admin is now a global context that you can use in the project.
> Added in tag verifications, updated file upload locations, and fixed a weird problem with admin roles

- src/pages/StartupScreen/Startup.css
- src/pages/StartupScreen/Startup.jsx
- src/pages/StartupScreen/components/ForgotPassword.jsx
make sure you can navigate through the login to sign up to forgot password and be sure that the proper messages pop up for those situations
> fixed startup styling again

- src/App.jsx
- src/config/userContext.js
- src/pages/Home/Home.jsx
- src/pages/Home/components/FileSearchComponents/File.jsx
- src/pages/Home/components/FileSearchComponents/FileSearchPage.jsx
- src/pages/StartupScreen/Startup.jsx
- src/pages/StartupScreen/components/ForgotPassword.jsx
- src/pages/StartupScreen/components/Login.jsx
- src/pages/StartupScreen/components/Signup.jsx
Is rudimentary but want to get it out so I can start paying attention in class
> Implemented File Pulling
